#!/usr/bin/env python3
"""API endpoint check - hits URLs and reports status codes and response times.

Generated by yburn. Standalone script, no yburn dependency needed.
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error

CONFIG = {
    "telegram_token": os.environ.get("YBURN_TELEGRAM_TOKEN", ""),
    "telegram_chat_id": os.environ.get("YBURN_TELEGRAM_CHAT_ID", ""),
    "endpoints": [],
    "timeout_seconds": 10,
    "expected_status": 200,
}


def check_endpoint(url, timeout, expected_status):
    """Check a single endpoint."""
    result = {"url": url, "ok": False}
    start = time.time()
    try:
        req = urllib.request.Request(url, method="GET")
        req.add_header("User-Agent", "yburn-health-check/1.0")
        resp = urllib.request.urlopen(req, timeout=timeout)
        elapsed = (time.time() - start) * 1000
        result["status_code"] = resp.status
        result["response_ms"] = round(elapsed)
        result["ok"] = resp.status == expected_status
        if not result["ok"]:
            result["issue"] = f"Expected {expected_status}, got {resp.status}"
    except urllib.error.HTTPError as e:
        elapsed = (time.time() - start) * 1000
        result["status_code"] = e.code
        result["response_ms"] = round(elapsed)
        result["issue"] = f"HTTP {e.code}: {e.reason}"
    except urllib.error.URLError as e:
        elapsed = (time.time() - start) * 1000
        result["response_ms"] = round(elapsed)
        result["issue"] = f"Connection failed: {e.reason}"
    except Exception as e:
        elapsed = (time.time() - start) * 1000
        result["response_ms"] = round(elapsed)
        result["issue"] = str(e)
    return result


def send_output(message):
    """Send output via Telegram or print to stdout."""
    token = CONFIG["telegram_token"]
    chat_id = CONFIG["telegram_chat_id"]
    if token and chat_id:
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        data = json.dumps({
            "chat_id": chat_id, "text": message, "parse_mode": "Markdown",
        }).encode()
        req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
        try:
            urllib.request.urlopen(req)
        except Exception as e:
            print(f"Telegram failed: {e}", file=sys.stderr)
            print(message)
    else:
        print(message)


def main():
    """Check all endpoints and send report."""
    if not CONFIG["endpoints"]:
        send_output("⚠️ *API Endpoint Check*\nNo endpoints configured.")
        return 1

    results = []
    for url in CONFIG["endpoints"]:
        results.append(check_endpoint(url, CONFIG["timeout_seconds"], CONFIG["expected_status"]))

    all_ok = all(r["ok"] for r in results)
    lines = ["🌐 *API Endpoint Check*", ""]

    for r in results:
        status = "✅" if r["ok"] else "🔴"
        ms = f"{r['response_ms']}ms" if "response_ms" in r else "N/A"
        code = r.get("status_code", "N/A")
        lines.append(f"{status} `{r['url']}`")
        lines.append(f"  Status: {code} | Response: {ms}")
        if "issue" in r:
            lines.append(f"  Issue: {r['issue']}")
        lines.append("")

    if all_ok:
        lines.append(f"✅ *All {len(results)} endpoint(s) healthy*")
    else:
        down = sum(1 for r in results if not r["ok"])
        lines.append(f"🔴 *{down}/{len(results)} endpoint(s) DOWN*")

    send_output("\n".join(lines))
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
