#!/usr/bin/env python3
"""File watcher - checks if specified files changed since last run.

Generated by yburn. Standalone script, no yburn dependency needed.
"""

import hashlib
import json
import os
import sys
from datetime import datetime

CONFIG = {
    "telegram_token": os.environ.get("YBURN_TELEGRAM_TOKEN", ""),
    "telegram_chat_id": os.environ.get("YBURN_TELEGRAM_CHAT_ID", ""),
    "watch_paths": [],
    "state_dir": os.path.expanduser("~/.yburn/state"),
}

STATE_FILE = "file-watcher-state.json"


def get_file_hash(path):
    """Get SHA256 hash of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def get_file_info(path):
    """Get file metadata."""
    expanded = os.path.expanduser(path)
    if not os.path.exists(expanded):
        return {"exists": False, "path": path}
    stat = os.stat(expanded)
    return {
        "exists": True,
        "path": path,
        "size": stat.st_size,
        "mtime": stat.st_mtime,
        "hash": get_file_hash(expanded),
    }


def load_state():
    """Load previous file state."""
    state_path = os.path.join(CONFIG["state_dir"], STATE_FILE)
    if os.path.exists(state_path):
        try:
            with open(state_path) as f:
                return json.load(f)
        except Exception:
            return {}
    return {}


def save_state(state):
    """Save current file state."""
    os.makedirs(CONFIG["state_dir"], exist_ok=True)
    state_path = os.path.join(CONFIG["state_dir"], STATE_FILE)
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2)


def send_output(message):
    """Send output via Telegram or print to stdout."""
    token = CONFIG["telegram_token"]
    chat_id = CONFIG["telegram_chat_id"]
    if token and chat_id:
        import urllib.request
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        data = json.dumps({
            "chat_id": chat_id, "text": message, "parse_mode": "Markdown",
        }).encode()
        req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
        try:
            urllib.request.urlopen(req)
        except Exception as e:
            print(f"Telegram failed: {e}", file=sys.stderr)
            print(message)
    else:
        print(message)


def format_size(size_bytes):
    """Format bytes to human readable."""
    for unit in ["B", "KB", "MB", "GB"]:
        if size_bytes < 1024:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024
    return f"{size_bytes:.1f} TB"


def main():
    """Check files for changes and report."""
    if not CONFIG["watch_paths"]:
        send_output("⚠️ *File Watcher*\nNo files configured to watch.")
        return 1

    prev_state = load_state()
    new_state = {}
    changes = []
    missing = []

    for path in CONFIG["watch_paths"]:
        info = get_file_info(path)
        new_state[path] = info

        if not info["exists"]:
            missing.append(path)
            continue

        prev = prev_state.get(path)
        if prev is None:
            changes.append({"path": path, "type": "new", "info": info})
        elif not prev.get("exists"):
            changes.append({"path": path, "type": "created", "info": info})
        elif prev.get("hash") != info["hash"]:
            size_diff = info["size"] - prev.get("size", 0)
            changes.append({
                "path": path,
                "type": "modified",
                "info": info,
                "size_diff": size_diff,
            })

    save_state(new_state)

    if not changes and not missing:
        # No changes, silent success
        return 0

    lines = ["📁 *File Watcher Report*", ""]

    if changes:
        lines.append("*Changes Detected:*")
        for c in changes:
            name = os.path.basename(c["path"])
            if c["type"] == "modified":
                diff = c.get("size_diff", 0)
                diff_str = f"+{format_size(diff)}" if diff > 0 else f"-{format_size(abs(diff))}" if diff < 0 else "same size"
                lines.append(f"  ✏️ {name} (modified, {diff_str})")
            elif c["type"] in ("new", "created"):
                lines.append(f"  🆕 {name} ({c['type']}, {format_size(c['info']['size'])})")
        lines.append("")

    if missing:
        lines.append("*Missing Files:*")
        for path in missing:
            lines.append(f"  ❌ {os.path.basename(path)} (`{path}`)")
        lines.append("")

    lines.append(f"Watching {len(CONFIG['watch_paths'])} file(s)")
    send_output("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
