# Generated by yburn from template: cron-health-report
# Original cron job: [yburn] Weekly Cron Health Audit (ID: cad28116-b26d-4085-8c9c-e0892b64e1bc)
# Schedule: 30 4 * * 0 (America/New_York)
#
#!/usr/bin/env python3
"""Cron health report - lists all cron jobs and their status.

Generated by yburn. Standalone script, no yburn dependency needed.
"""

import json
import os
import subprocess
import sys

CONFIG = {
    "telegram_token": os.environ.get("YBURN_TELEGRAM_TOKEN", ""),
    "telegram_chat_id": os.environ.get("YBURN_TELEGRAM_CHAT_ID", ""),
    "include_disabled": True,
}


def get_cron_jobs():
    """Fetch cron jobs from openclaw."""
    try:
        result = subprocess.run(
            ["openclaw", "cron", "list", "--json"],
            capture_output=True, text=True, check=True,
        )
        data = json.loads(result.stdout)
        if isinstance(data, dict) and "jobs" in data:
            return data["jobs"]
        return data if isinstance(data, list) else []
    except Exception as e:
        print(f"Failed to fetch cron jobs: {e}", file=sys.stderr)
        return []


def send_output(message):
    """Send output via Telegram or print to stdout."""
    token = CONFIG["telegram_token"]
    chat_id = CONFIG["telegram_chat_id"]

    if token and chat_id:
        import urllib.request
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        # Split long messages
        chunks = []
        if len(message) > 4000:
            lines = message.split("\n")
            chunk = []
            length = 0
            for line in lines:
                if length + len(line) + 1 > 4000:
                    chunks.append("\n".join(chunk))
                    chunk = [line]
                    length = len(line)
                else:
                    chunk.append(line)
                    length += len(line) + 1
            if chunk:
                chunks.append("\n".join(chunk))
        else:
            chunks = [message]

        for chunk in chunks:
            data = json.dumps({
                "chat_id": chat_id,
                "text": chunk,
                "parse_mode": "Markdown",
            }).encode()
            req = urllib.request.Request(
                url, data=data,
                headers={"Content-Type": "application/json"},
            )
            try:
                urllib.request.urlopen(req)
            except Exception as e:
                print(f"Telegram send failed: {e}", file=sys.stderr)
                print(chunk)
    else:
        print(message)


def main():
    """Generate and send cron health report."""
    jobs = get_cron_jobs()
    if not jobs:
        send_output("⚠️ *Cron Health Report*\nNo cron jobs found or failed to fetch.")
        return 1

    enabled = [j for j in jobs if j.get("enabled", True)]
    disabled = [j for j in jobs if not j.get("enabled", True)]

    ok_jobs = []
    error_jobs = []
    for j in enabled:
        state = j.get("state", {})
        status = state.get("lastRunStatus", "unknown")
        errors = state.get("consecutiveErrors", 0)
        if status == "ok" and errors == 0:
            ok_jobs.append(j)
        else:
            error_jobs.append(j)

    lines = [
        "📊 *Cron Health Report*",
        "",
        f"*Total:* {len(jobs)} jobs",
        f"*Enabled:* {len(enabled)} | *Disabled:* {len(disabled)}",
        f"*Healthy:* {len(ok_jobs)} | *Errors:* {len(error_jobs)}",
        "",
    ]

    if error_jobs:
        lines.append("🔴 *Jobs with Errors:*")
        for j in error_jobs:
            name = j.get("name", j.get("id", "unknown"))
            state = j.get("state", {})
            status = state.get("lastRunStatus", "unknown")
            errors = state.get("consecutiveErrors", 0)
            last_error = state.get("lastError", "")
            lines.append(f"  - {name}: {status} ({errors} consecutive errors)")
            if last_error:
                lines.append(f"    Error: {last_error[:100]}")
        lines.append("")

    if CONFIG["include_disabled"] and disabled:
        lines.append(f"⏸️ *Disabled Jobs ({len(disabled)}):*")
        for j in disabled:
            name = j.get("name", j.get("id", "unknown"))
            lines.append(f"  - {name}")
        lines.append("")

    if not error_jobs:
        lines.append("✅ *All enabled cron jobs healthy*")
    else:
        lines.append(f"⚠️ *{len(error_jobs)} job(s) need attention*")

    send_output("\n".join(lines))
    return 0 if not error_jobs else 1


if __name__ == "__main__":
    sys.exit(main())
