# Generated by yburn from template: git-backup-status
# Original cron job: [yburn] Nightly Backup + Git Commit (ID: 82e84b0f-3704-40f0-8573-d21d85f12509)
# Schedule: 45 22 * * * (America/New_York)
#
#!/usr/bin/env python3
"""Git backup status - checks repos for stale commits, dirty files, unpushed work.

Generated by yburn. Standalone script, no yburn dependency needed.
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone

CONFIG = {
    "telegram_token": os.environ.get("YBURN_TELEGRAM_TOKEN", ""),
    "telegram_chat_id": os.environ.get("YBURN_TELEGRAM_CHAT_ID", ""),
    "repo_paths": [],
    "stale_hours": 48,
}


def check_repo(path):
    """Check a single git repo's status."""
    result = {"path": path, "issues": [], "ok": True}
    expanded = os.path.expanduser(path)

    if not os.path.isdir(os.path.join(expanded, ".git")):
        result["issues"].append("Not a git repo")
        result["ok"] = False
        return result

    try:
        # Last commit date
        r = subprocess.run(
            ["git", "-C", expanded, "log", "-1", "--format=%ci"],
            capture_output=True, text=True, check=True,
        )
        last_commit_str = r.stdout.strip()
        if last_commit_str:
            last_commit = datetime.fromisoformat(last_commit_str)
            now = datetime.now(timezone.utc)
            last_commit_utc = last_commit.astimezone(timezone.utc)
            hours_ago = (now - last_commit_utc).total_seconds() / 3600
            result["last_commit"] = last_commit_str
            result["hours_ago"] = round(hours_ago, 1)
            if hours_ago > CONFIG["stale_hours"]:
                result["issues"].append(f"Last commit {result['hours_ago']}h ago (threshold: {CONFIG['stale_hours']}h)")
                result["ok"] = False
        else:
            result["issues"].append("No commits found")
            result["ok"] = False

        # Dirty files
        r = subprocess.run(
            ["git", "-C", expanded, "status", "--porcelain"],
            capture_output=True, text=True,
        )
        dirty = [l for l in r.stdout.strip().split("\n") if l.strip()]
        if dirty:
            result["dirty_count"] = len(dirty)
            result["issues"].append(f"{len(dirty)} uncommitted file(s)")
            result["ok"] = False
        else:
            result["dirty_count"] = 0

        # Unpushed commits
        r = subprocess.run(
            ["git", "-C", expanded, "log", "--oneline", "@{u}..HEAD"],
            capture_output=True, text=True,
        )
        if r.returncode == 0:
            unpushed = [l for l in r.stdout.strip().split("\n") if l.strip()]
            if unpushed:
                result["unpushed"] = len(unpushed)
                result["issues"].append(f"{len(unpushed)} unpushed commit(s)")
                result["ok"] = False
            else:
                result["unpushed"] = 0
        else:
            result["unpushed"] = 0

    except Exception as e:
        result["issues"].append(f"Error: {e}")
        result["ok"] = False

    return result


def send_output(message):
    """Send output via Telegram or print to stdout."""
    token = CONFIG["telegram_token"]
    chat_id = CONFIG["telegram_chat_id"]
    if token and chat_id:
        import urllib.request
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        data = json.dumps({
            "chat_id": chat_id, "text": message, "parse_mode": "Markdown",
        }).encode()
        req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
        try:
            urllib.request.urlopen(req)
        except Exception as e:
            print(f"Telegram failed: {e}", file=sys.stderr)
            print(message)
    else:
        print(message)


def main():
    """Check all repos and send report."""
    if not CONFIG["repo_paths"]:
        send_output("⚠️ *Git Backup Status*\nNo repos configured.")
        return 1

    results = []
    for path in CONFIG["repo_paths"]:
        try:
            results.append(check_repo(path))
        except Exception as e:
            results.append({"path": path, "issues": [str(e)], "ok": False})

    all_ok = all(r["ok"] for r in results)
    lines = ["📦 *Git Backup Status*", ""]

    for r in results:
        name = os.path.basename(r["path"])
        status = "✅" if r["ok"] else "⚠️"
        lines.append(f"{status} *{name}* (`{r['path']}`)")
        if r.get("last_commit"):
            lines.append(f"  Last commit: {r['hours_ago']}h ago")
        if r.get("dirty_count", 0) > 0:
            lines.append(f"  Dirty files: {r['dirty_count']}")
        if r.get("unpushed", 0) > 0:
            lines.append(f"  Unpushed: {r['unpushed']}")
        if r["issues"]:
            for issue in r["issues"]:
                lines.append(f"  🔸 {issue}")
        lines.append("")

    if all_ok:
        lines.append("✅ *All repos healthy*")
    else:
        problem_count = sum(1 for r in results if not r["ok"])
        lines.append(f"⚠️ *{problem_count} repo(s) need attention*")

    send_output("\n".join(lines))
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
