# Generated by yburn from template: system-diagnostics
# Original cron job: [yburn] Nightly System Diagnostic (ID: aa55f515-504d-4df2-a924-1d3782938624)
# Schedule: 0 4 * * * (America/New_York)
#
#!/usr/bin/env python3
"""System diagnostics - collects disk, CPU, memory, uptime, process status.

Generated by yburn. Standalone script, no yburn dependency needed.
"""

import os
import platform
import shutil
import subprocess
import sys

# --- CONFIG (filled by yburn converter) ---
CONFIG = {
    "telegram_token": os.environ.get("YBURN_TELEGRAM_TOKEN", ""),
    "telegram_chat_id": os.environ.get("YBURN_TELEGRAM_CHAT_ID", ""),
    "processes_to_check": [],
    "disk_threshold_pct": 80,
}


def get_uptime():
    """Get system uptime."""
    try:
        result = subprocess.run(["uptime"], capture_output=True, text=True)
        return result.stdout.strip()
    except Exception:
        return "unavailable"


def get_load_average():
    """Get load average."""
    try:
        load = os.getloadavg()
        return f"{load[0]:.2f}, {load[1]:.2f}, {load[2]:.2f}"
    except Exception:
        return "unavailable"


def get_disk_usage():
    """Get disk usage for all mounted volumes."""
    results = []
    alerts = []
    try:
        result = subprocess.run(
            ["df", "-h"], capture_output=True, text=True
        )
        lines = result.stdout.strip().split("\n")
        for line in lines[1:]:
            parts = line.split()
            if len(parts) >= 5 and "%" in parts[4]:
                pct = int(parts[4].replace("%", ""))
                mount = parts[-1]
                size = parts[1]
                used = parts[2]
                avail = parts[3]
                status = "🔴" if pct >= CONFIG["disk_threshold_pct"] else "✅"
                results.append(f"  {status} {mount}: {pct}% ({used}/{size}, {avail} free)")
                if pct >= CONFIG["disk_threshold_pct"]:
                    alerts.append(f"{mount} at {pct}%")
    except Exception as e:
        results.append(f"  Error: {e}")
    return results, alerts


def get_memory():
    """Get memory usage."""
    try:
        if platform.system() == "Darwin":
            result = subprocess.run(
                ["vm_stat"], capture_output=True, text=True
            )
            lines = result.stdout.strip().split("\n")
            stats = {}
            for line in lines[1:]:
                if ":" in line:
                    key, val = line.split(":", 1)
                    val = val.strip().rstrip(".")
                    try:
                        stats[key.strip()] = int(val)
                    except ValueError:
                        pass
            page_size = 16384
            free = stats.get("Pages free", 0) * page_size
            active = stats.get("Pages active", 0) * page_size
            inactive = stats.get("Pages inactive", 0) * page_size
            wired = stats.get("Pages wired down", 0) * page_size
            total_used = (active + wired) / (1024**3)
            total_free = (free + inactive) / (1024**3)
            return f"{total_used:.1f} GB used, {total_free:.1f} GB free"
        else:
            result = subprocess.run(
                ["free", "-h"], capture_output=True, text=True
            )
            return result.stdout.strip().split("\n")[1]
    except Exception:
        return "unavailable"


def get_cpu():
    """Get CPU usage."""
    try:
        if platform.system() == "Darwin":
            result = subprocess.run(
                ["top", "-l", "1", "-n", "0", "-s", "0"],
                capture_output=True, text=True
            )
            for line in result.stdout.split("\n"):
                if "CPU usage" in line:
                    return line.strip()
            return "unavailable"
        else:
            result = subprocess.run(
                ["top", "-bn1"], capture_output=True, text=True
            )
            for line in result.stdout.split("\n"):
                if "Cpu" in line:
                    return line.strip()
            return "unavailable"
    except Exception:
        return "unavailable"


def check_processes():
    """Check if specified processes are running."""
    results = []
    for proc_name in CONFIG["processes_to_check"]:
        try:
            result = subprocess.run(
                ["pgrep", "-f", proc_name],
                capture_output=True, text=True
            )
            if result.returncode == 0:
                pids = result.stdout.strip().split("\n")
                results.append(f"  ✅ {proc_name} (PID: {', '.join(pids[:3])})")
            else:
                results.append(f"  🔴 {proc_name} NOT RUNNING")
        except Exception:
            results.append(f"  ⚠️ {proc_name} (check failed)")
    return results


def send_output(message):
    """Send output via Telegram or print to stdout."""
    token = CONFIG["telegram_token"]
    chat_id = CONFIG["telegram_chat_id"]

    if token and chat_id:
        import urllib.request
        import json
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        data = json.dumps({
            "chat_id": chat_id,
            "text": message,
            "parse_mode": "Markdown",
        }).encode()
        req = urllib.request.Request(
            url, data=data,
            headers={"Content-Type": "application/json"},
        )
        try:
            urllib.request.urlopen(req)
        except Exception as e:
            print(f"Telegram send failed: {e}", file=sys.stderr)
            print(message)
    else:
        print(message)


def main():
    """Run system diagnostics and send report."""
    sections = []

    # Header
    sections.append("🖥️ *System Diagnostics*")
    sections.append("")

    # Uptime
    try:
        sections.append(f"*Uptime:* {get_uptime()}")
    except Exception:
        sections.append("*Uptime:* unavailable")

    # Load
    try:
        sections.append(f"*Load:* {get_load_average()}")
    except Exception:
        sections.append("*Load:* unavailable")

    # CPU
    try:
        sections.append(f"*CPU:* {get_cpu()}")
    except Exception:
        sections.append("*CPU:* unavailable")

    # Memory
    try:
        sections.append(f"*Memory:* {get_memory()}")
    except Exception:
        sections.append("*Memory:* unavailable")

    # Disk
    sections.append("")
    sections.append("*Disk Usage:*")
    try:
        disk_lines, disk_alerts = get_disk_usage()
        sections.extend(disk_lines)
    except Exception:
        sections.append("  unavailable")
        disk_alerts = []

    # Processes
    if CONFIG["processes_to_check"]:
        sections.append("")
        sections.append("*Processes:*")
        try:
            proc_lines = check_processes()
            sections.extend(proc_lines)
        except Exception:
            sections.append("  check failed")

    # Status
    sections.append("")
    if disk_alerts:
        sections.append(f"⚠️ *ALERT:* Disk threshold exceeded: {', '.join(disk_alerts)}")
    else:
        sections.append("✅ *Status:* All systems nominal")

    message = "\n".join(sections)
    send_output(message)

    return 0 if not disk_alerts else 1


if __name__ == "__main__":
    sys.exit(main())
